all:
	pdflatex reaction-paper
	bibtex reaction-paper
	pdflatex reaction-paper
	pdflatex reaction-paper
clean:
	rm reaction-paper.aux
	rm reaction-paper.log
	rm reaction-paper.out
	rm reaction-paper.pdf
	rm texput.log
lite:
	xelatex reaction-paper
